# Generated by Django 4.2.7 on 2026-04-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_riderecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderecording',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
