# Generated by Django 4.2.7 on 2026-04-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_riderecording_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderecording',
            name='audio_output',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
