# Generated by Django 4.2.7 on 2026-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_riderecording_audio_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="current_location",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="customer_acknowledged_completion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ride",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("ongoing", "Ongoing"),
                    ("awaiting_ack", "Awaiting customer acknowledgment"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
