# Generated by Django 4.2.7 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_ride_flow_otp_and_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="customer_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="customer_rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="payment_method",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
