# Generated by Django 6.0.2 on 2026-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acknowledged_by_driver',
            field=models.BooleanField(default=False),
        ),
    ]
