# Generated by Django 4.2.7 on 2026-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_acknowledged_by_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adminreply',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
    ]
