# Generated by Django 4.2.7 on 2026-05-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_audio_url_alter_adminreply_voice_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminreply",
            name="audio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="adminreply",
            name="voice_note",
            field=models.FileField(blank=True, null=True, upload_to="voice_notes/"),
        ),
    ]
