# Generated by Django 4.2.7 on 2026-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_adminreply_audio_url_alter_adminreply_voice_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="resolution_for_customer",
            field=models.TextField(blank=True),
        ),
    ]
