# Generated by Django 4.2.7 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ride_flow_otp_and_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminreply",
            name="audio_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
